### ISSUE TITLE
A Plasmo VC version of this mod would be nice.

### ISSUE THREAD

**Issue by MagmaSlime123** [kikugie/voicechat-soundboard#1]

**Comment by kikugie** [comment]
Agreed (its WIP)

**Comment by MagmaSlime123** [comment]
Plasmo is also much more feature rich compared to SVC. SVC doesn't have many addons.

**Comment by kikugie** [comment]
As already said, I am already working on a solution that would account for both mods, but I'm personally using SVC and it is simply more popular, so it was a primary target.
