### ISSUE TITLE
The sounds stop working

### ISSUE THREAD

**Issue by djOB2EOTWQW1** [kikugie/voicechat-soundboard#12]
When I turn on music, it turns off after a while, even though it hasn't even gotten to the end.

**Comment by kikugie** [comment]
How long of a while? I tested it with several minute long tracks and it works

**Comment by djOB2EOTWQW1** [comment]
So, I've been running around a bit with tab activated, and I can say that the song is interrupted when a player leaves the server. Maybe it depends on the specific server, but yeah

**Comment by djOB2EOTWQW1** [comment]
https://youtu.be/_k1hOWAXBDQ

**Comment by djOB2EOTWQW1** [comment]
And yes, it also happens on its own, regardless of whether players have logged off the server. I don't know what it is :D
