### ISSUE TITLE
Sounds not playing

### ISSUE THREAD

**Issue by HOPSlodge** [kikugie/voicechat-soundboard#14]
I am on version 1.21 but whenever i click on any sound i click it doesnt play and all my sound files are in .wav format.

**Comment by kikugie** [comment]
You need to be unmuted and not have push to talk

**Comment by HOPSlodge** [comment]
yes i am unmuted and i am not on push to talk i tried both singleplayer and multiplayer but sounds are not working

**Comment by kikugie** [comment]
Will be fixed in the next update
