### ISSUE TITLE
RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'soundboard'!

### ISSUE THREAD

**Issue by FuchsXithub** [kikugie/voicechat-soundboard#3]
Help me please, my Pack is crashing every time i start!

This can help:
![image](https://github.com/kikugie/voicechat-soundboard/assets/149900409/32492590-5ad7-458a-8c0c-cd83c6e64f9e)

**Comment by kikugie** [comment]
Please read the message there. You have an outdated version of Simple Voice
Chat, which is not compatible with the mod.

**Comment by FuchsXithub** [comment]
> Please read the message there. You have an outdated version of Simple Voice Chat, which is not compatible with the mod.

This is the lastest Version on Modrinth & the v1.20
I read the messages.

**Comment by kikugie** [comment]
Really?
https://modrinth.com/plugin/simple-voice-chat/version/fabric-1.20.1-2.5.13

**Comment by FuchsXithub** [comment]
I have tested all Versions ^^

**Comment by kikugie** [comment]
No idea how you tested, but the message you initially got is designed to show up only if your voice chat is outdated. It does not occur with the latest version.

**Comment by kikugie** [comment]
Closing as invalid, since the error message is intentional for outdated voicechat builds.
