### ISSUE TITLE
1.21 sounboard isnt working

### ISSUE THREAD

**Issue by eowtheca** [kikugie/voicechat-soundboard#5]
at first i thought it was conflicting with my other mods, but after testing the soundboard just on its own it still wasnt working.... when i join the game and open soundboard menu, it doesnt show the sounds, even though i put my audio files in the right place.  i tried deleting the soundboard folder for the mod to create it again, but that didnt work either

![image](https://github.com/kikugie/voicechat-soundboard/assets/55887091/bc694d73-d5a8-4e99-8fbf-f56c3c85a2bc)
![image](https://github.com/kikugie/voicechat-soundboard/assets/55887091/331f967d-3a65-48c5-b067-b2b19faebac3)

**Comment by kikugie** [comment]
You need `.wav` files

**Comment by SplendidAlakey** [comment]
The mod page says:
> Accepted formats are mp3 and wav.

Converting the mp3 to wav makes it show up on the list, but the sound is still not playing.
The sound in question, if that matters: [cheese.zip](https://github.com/user-attachments/files/16235158/cheese.zip)

**Comment by kikugie** [comment]
It can't send the sound if you're muted

**Comment by SplendidAlakey** [comment]
Not muted, checked that too. I do usually use push-to-talk, but I tried voice activation and it still produced no sound when I tried clicking and shift-clicking it.

**Comment by SplendidAlakey** [comment]
Never mind, complete mistake on my part. I was trying it in single-player and VC disabled in local worlds in SVC settings...

Case closed for me, but do update the mod page to remove the mp3 as a valid file.
