### ISSUE TITLE
Audio stops playing after certain duration

### ISSUE THREAD

**Issue by LordEnder-Kitty** [kikugie/voicechat-soundboard#6]
I haven't figured out the exact time that it does it, but a couple minutes into playing something, it just stops. Idk if this is intentional for some reason, but it is extremely annoying. It intrudes on my ability to drive by someone when ice boat racing while blasting Back In Black.

**Comment by kikugie** [comment]
If possible, can you send the audio you used, so I can test with it?

**Comment by kikugie** [comment]
Ok, I figured - the audio end is not calculated properly, so it plays half the sound. Whoops

**Comment by kikugie** [comment]
Published 0.5
