### ISSUE TITLE
idk how to fix this owo-ui error

### ISSUE THREAD

**Issue by DaAquaDuck** [kikugie/voicechat-soundboard#8]
![2024-08-15_21 29 32](https://github.com/user-attachments/assets/2a0d1220-9b4f-418d-974b-d0e88a10479d)

**Comment by kikugie** [comment]
This might've been caused by a resource reload error or corrupted audio file. Please send a full game log.

**Comment by DaAquaDuck** [comment]
Fixed it just redownloaded the mod
